// <auto-generated />
using GeekBurger.StoreCatalog.Infra.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GeekBurger.StoreCatalog.Infra.Migrations
{
    [DbContext(typeof(StoreCatalogDbContext))]
    partial class StoreCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeekBurger.StoreCatalog.Contract.ProductionAreas", b =>
                {
                    b.Property<Guid>("ProductionAreaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ListRestrictions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("Status");

                    b.HasKey("ProductionAreaId");

                    b.ToTable("ProductionsAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
